rm wArpResults/PDBs/2gm6-2.0-parrot-noncs.pdb 
rm wArpResults/ArpLogs/2gm6-2.0-parrot-noncs.txt 
rm wArpResults/IntermediatePDBs/2gm6-2.0-parrot-noncs.pdb 
rm wArpResults/IntermediateLogs/2gm6-2.0-parrot-noncs.txt 
rm wArpResults/PDBs/2gnr-1.8-parrot-noncs.pdb 
rm wArpResults/ArpLogs/2gnr-1.8-parrot-noncs.txt 
rm wArpResults/IntermediatePDBs/2gnr-1.8-parrot-noncs.pdb 
rm wArpResults/IntermediateLogs/2gnr-1.8-parrot-noncs.txt 
rm wArpResults/PDBs/2gvh-2.6-parrot-noncs.pdb 
rm wArpResults/ArpLogs/2gvh-2.6-parrot-noncs.txt 
rm wArpResults/IntermediatePDBs/2gvh-2.6-parrot-noncs.pdb 
rm wArpResults/IntermediateLogs/2gvh-2.6-parrot-noncs.txt 
rm wArpResults/PDBs/2hx1-2.1-parrot-noncs.pdb 
rm wArpResults/ArpLogs/2hx1-2.1-parrot-noncs.txt 
rm wArpResults/IntermediatePDBs/2hx1-2.1-parrot-noncs.pdb 
rm wArpResults/IntermediateLogs/2hx1-2.1-parrot-noncs.txt 
rm wArpResults/PDBs/2ich-2.0-parrot-noncs.pdb 
rm wArpResults/ArpLogs/2ich-2.0-parrot-noncs.txt 
rm wArpResults/IntermediatePDBs/2ich-2.0-parrot-noncs.pdb 
rm wArpResults/IntermediateLogs/2ich-2.0-parrot-noncs.txt 
rm wArpResults/PDBs/2ig6-1.8-parrot-noncs.pdb 
rm wArpResults/ArpLogs/2ig6-1.8-parrot-noncs.txt 
rm wArpResults/IntermediatePDBs/2ig6-1.8-parrot-noncs.pdb 
rm wArpResults/IntermediateLogs/2ig6-1.8-parrot-noncs.txt 
rm wArpResults/PDBs/2iiu-3.8-parrot-noncs.pdb 
rm wArpResults/ArpLogs/2iiu-3.8-parrot-noncs.txt 
rm wArpResults/IntermediatePDBs/2iiu-3.8-parrot-noncs.pdb 
rm wArpResults/IntermediateLogs/2iiu-3.8-parrot-noncs.txt 
rm wArpResults/PDBs/2nyh-1.7-parrot-noncs.pdb 
rm wArpResults/ArpLogs/2nyh-1.7-parrot-noncs.txt 
rm wArpResults/IntermediatePDBs/2nyh-1.7-parrot-noncs.pdb 
rm wArpResults/IntermediateLogs/2nyh-1.7-parrot-noncs.txt 
rm wArpResults/PDBs/2ou6-1.8-parrot-noncs.pdb 
rm wArpResults/ArpLogs/2ou6-1.8-parrot-noncs.txt 
rm wArpResults/IntermediatePDBs/2ou6-1.8-parrot-noncs.pdb 
rm wArpResults/IntermediateLogs/2ou6-1.8-parrot-noncs.txt 
rm wArpResults/PDBs/2ozj-1.6-parrot-noncs.pdb 
rm wArpResults/ArpLogs/2ozj-1.6-parrot-noncs.txt 
rm wArpResults/IntermediatePDBs/2ozj-1.6-parrot-noncs.pdb 
rm wArpResults/IntermediateLogs/2ozj-1.6-parrot-noncs.txt 
rm wArpResults/PDBs/2p8j-2.0-parrot-noncs.pdb 
rm wArpResults/ArpLogs/2p8j-2.0-parrot-noncs.txt 
rm wArpResults/IntermediatePDBs/2p8j-2.0-parrot-noncs.pdb 
rm wArpResults/IntermediateLogs/2p8j-2.0-parrot-noncs.txt 
rm wArpResults/PDBs/2pnk-3.4-parrot-noncs.pdb 
rm wArpResults/ArpLogs/2pnk-3.4-parrot-noncs.txt 
rm wArpResults/IntermediatePDBs/2pnk-3.4-parrot-noncs.pdb 
rm wArpResults/IntermediateLogs/2pnk-3.4-parrot-noncs.txt 
rm wArpResults/PDBs/2pnk-3.6-parrot-noncs.pdb 
rm wArpResults/ArpLogs/2pnk-3.6-parrot-noncs.txt 
rm wArpResults/IntermediatePDBs/2pnk-3.6-parrot-noncs.pdb 
rm wArpResults/IntermediateLogs/2pnk-3.6-parrot-noncs.txt 
rm wArpResults/PDBs/2prr-3.2-parrot-noncs.pdb 
rm wArpResults/ArpLogs/2prr-3.2-parrot-noncs.txt 
rm wArpResults/IntermediatePDBs/2prr-3.2-parrot-noncs.pdb 
rm wArpResults/IntermediateLogs/2prr-3.2-parrot-noncs.txt 
rm wArpResults/PDBs/2prr-3.4-parrot-noncs.pdb 
rm wArpResults/ArpLogs/2prr-3.4-parrot-noncs.txt 
rm wArpResults/IntermediatePDBs/2prr-3.4-parrot-noncs.pdb 
rm wArpResults/IntermediateLogs/2prr-3.4-parrot-noncs.txt 
rm wArpResults/PDBs/2prr-3.8-parrot-noncs.pdb 
rm wArpResults/ArpLogs/2prr-3.8-parrot-noncs.txt 
rm wArpResults/IntermediatePDBs/2prr-3.8-parrot-noncs.pdb 
rm wArpResults/IntermediateLogs/2prr-3.8-parrot-noncs.txt 
rm wArpResults/PDBs/2prr-4.0-parrot-noncs.pdb 
rm wArpResults/ArpLogs/2prr-4.0-parrot-noncs.txt 
rm wArpResults/IntermediatePDBs/2prr-4.0-parrot-noncs.pdb 
rm wArpResults/IntermediateLogs/2prr-4.0-parrot-noncs.txt 
