rm PhenixResults/PDBs/1vkd-3.6-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/1vkd-3.6-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/1vkd-3.6-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/1vkd-3.6-parrot-hancs.txt 
rm PhenixResults/PDBs/1vl0-2.5-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/1vl0-2.5-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/1vl0-2.5-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/1vl0-2.5-parrot-hancs.txt 
rm PhenixResults/PDBs/1vp4-1.8-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/1vp4-1.8-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/1vp4-1.8-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/1vp4-1.8-parrot-hancs.txt 
rm PhenixResults/PDBs/1vqs-1.8-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/1vqs-1.8-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/1vqs-1.8-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/1vqs-1.8-parrot-hancs.txt 
rm PhenixResults/PDBs/2aam-2.2-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2aam-2.2-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2aam-2.2-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2aam-2.2-parrot-hancs.txt 
rm PhenixResults/PDBs/2aam-3.2-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2aam-3.2-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2aam-3.2-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2aam-3.2-parrot-hancs.txt 
rm PhenixResults/PDBs/2aam-3.8-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2aam-3.8-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2aam-3.8-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2aam-3.8-parrot-hancs.txt 
rm PhenixResults/PDBs/2afb-2.0-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2afb-2.0-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2afb-2.0-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2afb-2.0-parrot-hancs.txt 
rm PhenixResults/PDBs/2anu-2.3-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2anu-2.3-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2anu-2.3-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2anu-2.3-parrot-hancs.txt 
rm PhenixResults/PDBs/2anu-3.6-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2anu-3.6-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2anu-3.6-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2anu-3.6-parrot-hancs.txt 
rm PhenixResults/PDBs/2hr2-2.5-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2hr2-2.5-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2hr2-2.5-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2hr2-2.5-parrot-hancs.txt 
rm PhenixResults/PDBs/2hr2-4.0-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2hr2-4.0-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2hr2-4.0-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2hr2-4.0-parrot-hancs.txt 
rm PhenixResults/PDBs/2iiu-2.3-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2iiu-2.3-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2iiu-2.3-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2iiu-2.3-parrot-hancs.txt 
rm PhenixResults/PDBs/2iiu-3.6-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2iiu-3.6-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2iiu-3.6-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2iiu-3.6-parrot-hancs.txt 
rm PhenixResults/PDBs/2iiu-3.8-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2iiu-3.8-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2iiu-3.8-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2iiu-3.8-parrot-hancs.txt 
rm PhenixResults/PDBs/2it9-1.9-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2it9-1.9-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2it9-1.9-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2it9-1.9-parrot-hancs.txt 
rm PhenixResults/PDBs/2nwv-3.2-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2nwv-3.2-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2nwv-3.2-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2nwv-3.2-parrot-hancs.txt 
rm PhenixResults/PDBs/2nyh-4.0-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2nyh-4.0-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2nyh-4.0-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2nyh-4.0-parrot-hancs.txt 
rm PhenixResults/PDBs/2o5r-3.2-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2o5r-3.2-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2o5r-3.2-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2o5r-3.2-parrot-hancs.txt 
rm PhenixResults/PDBs/2o5r-3.4-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2o5r-3.4-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2o5r-3.4-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2o5r-3.4-parrot-hancs.txt 
rm PhenixResults/PDBs/2o5r-3.6-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2o5r-3.6-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2o5r-3.6-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2o5r-3.6-parrot-hancs.txt 
rm PhenixResults/PDBs/2obn-2.3-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2obn-2.3-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2obn-2.3-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2obn-2.3-parrot-hancs.txt 
rm PhenixResults/PDBs/2obn-3.4-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2obn-3.4-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2obn-3.4-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2obn-3.4-parrot-hancs.txt 
rm PhenixResults/PDBs/2oyo-1.5-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2oyo-1.5-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2oyo-1.5-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2oyo-1.5-parrot-hancs.txt 
rm PhenixResults/PDBs/2ozg-3.4-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2ozg-3.4-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2ozg-3.4-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2ozg-3.4-parrot-hancs.txt 
rm PhenixResults/PDBs/2p10-2.1-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2p10-2.1-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2p10-2.1-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2p10-2.1-parrot-hancs.txt 
rm PhenixResults/PDBs/2p10-3.4-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2p10-3.4-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2p10-3.4-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2p10-3.4-parrot-hancs.txt 
rm PhenixResults/PDBs/2p10-3.6-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2p10-3.6-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2p10-3.6-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2p10-3.6-parrot-hancs.txt 
rm PhenixResults/PDBs/2p10-3.8-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2p10-3.8-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2p10-3.8-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2p10-3.8-parrot-hancs.txt 
rm PhenixResults/PDBs/2p10-4.0-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2p10-4.0-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2p10-4.0-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2p10-4.0-parrot-hancs.txt 
rm PhenixResults/PDBs/2p7i-1.7-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2p7i-1.7-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2p7i-1.7-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2p7i-1.7-parrot-hancs.txt 
rm PhenixResults/PDBs/2p7i-3.4-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2p7i-3.4-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2p7i-3.4-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2p7i-3.4-parrot-hancs.txt 
rm PhenixResults/PDBs/2p7i-3.8-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2p7i-3.8-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2p7i-3.8-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2p7i-3.8-parrot-hancs.txt 
rm PhenixResults/PDBs/2p97-3.8-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2p97-3.8-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2p97-3.8-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2p97-3.8-parrot-hancs.txt 
rm PhenixResults/PDBs/2pbl-3.2-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2pbl-3.2-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2pbl-3.2-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2pbl-3.2-parrot-hancs.txt 
rm PhenixResults/PDBs/2pbl-3.4-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2pbl-3.4-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2pbl-3.4-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2pbl-3.4-parrot-hancs.txt 
rm PhenixResults/PDBs/2pbl-3.6-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2pbl-3.6-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2pbl-3.6-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2pbl-3.6-parrot-hancs.txt 
rm PhenixResults/PDBs/2pgc-3.2-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2pgc-3.2-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2pgc-3.2-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2pgc-3.2-parrot-hancs.txt 
rm PhenixResults/PDBs/2pgc-3.6-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2pgc-3.6-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2pgc-3.6-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2pgc-3.6-parrot-hancs.txt 
rm PhenixResults/PDBs/2pgc-3.8-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2pgc-3.8-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2pgc-3.8-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2pgc-3.8-parrot-hancs.txt 
rm PhenixResults/PDBs/2pn1-3.2-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2pn1-3.2-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2pn1-3.2-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2pn1-3.2-parrot-hancs.txt 
rm PhenixResults/PDBs/2pnk-2.1-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2pnk-2.1-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2pnk-2.1-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2pnk-2.1-parrot-hancs.txt 
rm PhenixResults/PDBs/2pnk-3.4-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2pnk-3.4-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2pnk-3.4-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2pnk-3.4-parrot-hancs.txt 
rm PhenixResults/PDBs/2pnk-3.6-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2pnk-3.6-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2pnk-3.6-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2pnk-3.6-parrot-hancs.txt 
rm PhenixResults/PDBs/2pnk-3.8-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2pnk-3.8-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2pnk-3.8-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2pnk-3.8-parrot-hancs.txt 
rm PhenixResults/PDBs/2prr-3.4-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2prr-3.4-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2prr-3.4-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2prr-3.4-parrot-hancs.txt 
rm PhenixResults/PDBs/2prr-3.6-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2prr-3.6-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2prr-3.6-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2prr-3.6-parrot-hancs.txt 
rm PhenixResults/PDBs/2prv-1.3-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2prv-1.3-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2prv-1.3-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2prv-1.3-parrot-hancs.txt 
rm PhenixResults/PDBs/2prv-3.6-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2prv-3.6-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2prv-3.6-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2prv-3.6-parrot-hancs.txt 
rm PhenixResults/PDBs/1vkn-2.5-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/1vkn-2.5-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/1vkn-2.5-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/1vkn-2.5-parrot-hancs.txt 
rm PhenixResults/PDBs/1vli-2.4-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/1vli-2.4-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/1vli-2.4-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/1vli-2.4-parrot-hancs.txt 
rm PhenixResults/PDBs/1vr0-2.5-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/1vr0-2.5-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/1vr0-2.5-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/1vr0-2.5-parrot-hancs.txt 
rm PhenixResults/PDBs/2a2m-1.9-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2a2m-1.9-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2a2m-1.9-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2a2m-1.9-parrot-hancs.txt 
rm PhenixResults/PDBs/2fg0-1.8-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2fg0-1.8-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2fg0-1.8-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2fg0-1.8-parrot-hancs.txt 
rm PhenixResults/PDBs/2g0t-2.7-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2g0t-2.7-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2g0t-2.7-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2g0t-2.7-parrot-hancs.txt 
rm PhenixResults/PDBs/2oh1-1.5-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2oh1-1.5-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2oh1-1.5-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2oh1-1.5-parrot-hancs.txt 
rm PhenixResults/PDBs/2pbl-1.8-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2pbl-1.8-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2pbl-1.8-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2pbl-1.8-parrot-hancs.txt 
rm PhenixResults/PDBs/2prr-1.9-parrot-hancs.pdb 
rm PhenixResults/PhinexLogs/2prr-1.9-parrot-hancs.txt 
rm PhenixResults/IntermediatePDBs/2prr-1.9-parrot-hancs.pdb 
rm PhenixResults/IntermediateLogs/2prr-1.9-parrot-hancs.txt 
